routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('products', 'ProductController');

Route::resource('comments', 'CommentController');

Route::get('/product/search', 'ProductController@search')->name('product.search');

Route::get('/product/searchByExpDate', 'ProductController@searchByExpDate')->name('product.searchByExpDate');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Product extends Model
{
    use HasFactory;
    protected $fillable =
    [
        'user_id', 'name', 'image', 'category',
        'contact_info', 'cuantity', 'price',
        'expiration_date', 'sale1', 'sale2', 'sale3'
    ];


    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class ProductController extends Controller
{

    /**
     * Undocumented function
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Undocumented function
     *
     * @param Request $request
     * @return void
     */
    public function index(Request $request)
    {
        $now = Carbon::now();
        $products = Product::whereDate('expiration_date', '>', $now->toDateString())
            ->orderBy('views', 'desc')
            ->get();
        return view('product.index', compact('products'));
    }


    /**
     * Undocumented function
     *
     * @param Request $request
     * @return void
     */
    public function search(Request $request)
    {
        $search = $request->input('search');
        $products = Product::query()
            ->where('name', 'LIKE', "%{$search}%")
            ->orWhere('category', 'LIKE', "%{$search}%")
            ->get();

        return view('product.index', compact('products'));
    }


    /**
     * Undocumented function
     *
     * @param Request $request
     * @return void
     */
    public function searchByExpDate(Request $request)
    {
        $search = $request->input('search');
        $products = Product::query()
            ->where('expiration_date', 'LIKE', "%{$search}%")
            ->get();

        return view('product.index', compact('products'));
    }

    /**
     * Undocumented function
     *
     * @return void
     */
    public function create()
    {
        return view('product.create');
    }


    /**
     * Undocumented function
     *
     * @param Request $request
     * @return void
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'image' => 'required|image',
            'category' => 'required',
            'contact_info' => 'required',
            'cuantity' => 'required',
            'price' => 'required',
            'expiration_date' => 'required'
        ]);

        $image = $request->image;
        $newImage = time() . $image->getClientOriginalName();
        $image->move('uploads/images', $newImage);

        $id = Auth::id();
        $post = Product::create([
            'user_id' => $id,
            'name' => $request->name,
            'image' => 'uploads/images/' . $newImage,
            'category' => $request->category,
            'contact_info' => $request->contact_info,
            'cuantity' => $request->cuantity,
            'price' => $request->price,
            'expiration_date' => $request->expiration_date,
            'sale1' => ($request->price) - ($request->price * 30) / 100,
            'sale2' => ($request->price) - ($request->price * 50) / 100,
            'sale3' => ($request->price) - ($request->price * 70) / 100,
        ]);

        return redirect()->route('products.index');
    }


    /**
     * Undocumented function
     *
     * @param [type] $id
     * @return void
     */
    public function show($id)
    {
        $product = Product::find($id);
        $product->increment('views');
        $exp_date = Carbon::parse($product->expiration_date);
        $now = Carbon::now();
        $diff = $exp_date->diffInDays($now);

        return view('product.show')->with('product', $product)->with('diff', $diff);
    }

    /**
     * Undocumented function
     *
     * @param [type] $id
     * @return void
     */
    public function edit($id)
    {
        $product = Product::where('id', $id)->where('user_id', Auth::id())->first();
        if ($product === null) {
            return redirect()->back();
        }
        return view('product.edit')->with('product', $product);
    }


    /**
     * Undocumented function
     *
     * @param Request $request
     * @param [type] $id
     * @return void
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $this->validate($request, [
            'name' => 'required',
            'category' => 'required',
            'contact_info' => 'required',
            'cuantity' => 'required',
            'price' => 'required',
            'expiration_date' => 'required'
        ]);


        if ($request->has('image')) {
            $image = $request->image;
            $newImage = time() . $image->getClientOriginalName();
            $image->move('uploads/images', $newImage);
            $product->image = 'uploads/images/' . $newImage;
        }


        $product->name = $request->name;
        $product->category = $request->category;
        $product->contact_info = $request->contact_info;
        $product->cuantity = $request->cuantity;
        $product->price = $request->price;
        $product->expiration_date = $request->expiration_date;
        $product->sale1 = ($request->price) - ($request->price * 30) / 100;
        $product->sale2 = ($request->price) - ($request->price * 50) / 100;
        $product->sale3 = ($request->price) - ($request->price * 70) / 100;
        $product->save();

        return redirect()->route('products.index');
    }


    /**
     * Undocumented function
     *
     * @param [type] $id
     * @return void
     */
    public function destroy($id)
    {
        $product = Product::where('id', $id)->where('user_id', Auth::id())->first();
        if ($product === null) {
            return redirect()->back();
        }
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/product/comments.blade.php
@foreach ($comments as $item)
    <div @if ($item->parent_id != null) style ="margin-left:60px; color:red;" @endif>
        <strong>{{ $item->user->name }}</strong>
        <p>{{ $item->body }}</p>
        <form method="POST" action="{{ route('comments.store') }}">
            @csrf
            <div class="form-group">
                <textarea class="form-control" name="body" rows="3"></textarea>
                <input type="hidden" name="product_id" class="form-control" value="{{ $product_id }}">
                <input type="hidden" name="parent_id" class="form-control" value="{{ $item->id }}">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Reply </button>
            </div>
        </form>
        @include('product.comments' , ['comments'=>$item->replies])
    </div>
@endforeach

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
      <div class="col">
        <div class="container">
            <div class="jumbotron">
                <h1>Create Post</h1>
                <a href="{{route('products.index')}}" class="btn btn-primary">all products</a>
              </div>
        </div>
      </div>
    </div>
    <div class="row">
        @if (count($errors)>0)
        <ul>
            @foreach ($errors->all() as $item)
                <li>
                    {{$item}}
                </li>
            @endforeach
        </ul>
        @endif
      <div class="col">
        <div class="container">
            <form method="POST" action="{{route('products.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                  <label >Name</label>
                  <input type="text" name="name" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Image</label>
                    <input type="file" name="image" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Category</label>
                    <input type="text" name="category" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Cuantity</label>
                    <input type="text" name="cuantity" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Price</label>
                    <input type="text" name="price" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Contact Us</label>
                    <input type="text" name="contact_info" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Expiration Date</label>
                    <input type="date" name="expiration_date" class="form-control" >
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Save </button>
                </div>
              </form>
        </div>
      </div>
    </div>
</div>

@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
      <div class="col">
        <div class="container">
            <div class="jumbotron">
                <h1>Edit Post</h1>
                <a href="{{route('products.index')}}" class="btn btn-primary">all products</a>
              </div>
        </div>
      </div>
    </div>
    <div class="row">
        @if (count($errors)>0)
        <ul>
            @foreach ($errors->all() as $item)
                <li>
                    {{$item}}
                </li>
            @endforeach
        </ul>
        @endif
      <div class="col">
        <div class="container">
            <form method="POST" action="{{route('products.update',$product->id)}}" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                  <label >Name</label>
                  <input type="text" name="name" value="{{$product->name}}" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Image</label>
                    <input type="file" name="image" value="{{$product->image}}" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Category</label>
                    <input type="text" name="category" value="{{$product->category}}" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Cuantity</label>
                    <input type="text" name="cuantity" value="{{$product->cuantity}}" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Price</label>
                    <input type="text" name="price" value="{{$product->price}}" class="form-control" >
                </div>
                <div class="form-group">
                    <label >Contact Info</label>
                    <input type="text" name="contact_info" value="{{$product->contact_info}}" class="form-control" >
                  </div>
                <div class="form-group">
                    <label >Expiration Date</label>
                    <input type="date" name="expiration_date" value="{{$product->expiration_date}}" class="form-control" readonly="readonly" >
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Update </button>
                </div>
              </form>
        </div>
      </div>
    </div>
</div>

@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="container">
                    <div class="jumbotron">
                        <h1 class="display-4">All Products</h1>
                        <a href="{{ route('products.create') }}" class="btn btn-primary">Create Product</a>
                        <br>
                        <br>
                        <a href="{{ route('products.index') }}" class="btn btn-primary">All Product</a>
                        <br>
                        <br>
                        <div class="input-group">
                            <form action="{{ route('product.search') }}" method="GET">
                                <input type="text" name="search" placeholder="search by name or category" required />
                                <button type="submit" class="btn btn-primary">Search</button>
                            </form>
                        </div>
                        <br>
                        <div class="input-group">
                            <form action="{{ route('product.searchByExpDate') }}" method="GET">
                                <input type="date" name="search" placeholder="search by expiration date" required />
                                <button type="submit" class="btn btn-primary">Search</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @if ($products->count() > 0)
                <div class="col">
                    @php
                        $i = 0;
                    @endphp
                    <div class="container">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">name</th>
                                    <th scope="col">image</th>
                                    <th scope="col">category</th>
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($products as $item)
                                    <tr>
                                        <th scope="row">{{ ++$i }}</th>
                                        <td scope="col">{{ $item->name }}</td>
                                        <td scope="col">
                                            <!--  <img src="{{ '$item->photo' }}" alt="{{ $item->photo }}" class="img-tumbnail" width="50" height="50">-->
                                            <img src="{{ URL::asset($item->image) }}" alt="{{ $item->image }}"
                                                class="img-thumbnail" width="100" height="100">
                                        </td>
                                        <td scope="col"> {{ $item->category }}</td>
                                        <td scope="col">
                                            <a href="{{ route('products.show', $item->id) }}">show</a>&nbsp;&nbsp;
                                            @if ($item->user_id == Auth::id())
                                                <a href="{{ route('products.edit', $item->id) }}">edit</a>&nbsp;&nbsp;

                                                <div class="col-sm">
                                                    <form action="{{ route('products.destroy', $item->id) }}"
                                                        method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </div>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>
                        </table>

                    </div>
                </div>
            @else
                <div class="col">
                    <div class="alert alert-danger" role="alert">
                        No Products
                    </div>
                </div>
            @endif
        </div>




    </div>

@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="container">
                    <div class="card" style="width: 40rem;">
                        <img src="{{ URL::asset($product->image) }}" class="card-img-top" alt="{{ $product->image }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ $product->name }}</h5>
                            <p class="card-text">category: {{ $product->category }}</p>
                            <p class="card-text">Contact Us: {{ $product->contact_info }}</p>
                            <p class="card-text">cuantity: {{ $product->cuantity }}</p>
                            @if ($diff > 40)
                                <p class="card-text">Price: {{ $product->price }}$</p>
                            @elseif ($diff >= 30)
                                <span>Price: <del>{{ $product->price }}$ </del></span>
                                <p class="card-text">After30%: {{ $product->sale1 }}$</p>
                            @elseif ($diff >= 15)
                                <span>Price: <del>{{ $product->price }}$ </del></span>
                                <p class="card-text">After50%: {{ $product->sale2 }}$</p>
                            @elseif ($diff < 15)
                                <span>Price: <del>{{ $product->price }}$ </del></span>
                                <p class="card-text">After70%: {{ $product->sale3 }}$</p>
                            @endif
                            <p class="card-text">expiration date: {{ $product->expiration_date }}</p>
                            <p class="card-text">Views: {{ $product->views }}</p>


                            <hr>

                            <h4>comments</h4>
                            @include('product.comments' , ['comments'=>$product->comments, 'product_id'=>$product->id])

                            <hr>

                            <form method="POST" action="{{ route('comments.store') }}">
                                @csrf
                                <div class="form-group">
                                    <textarea class="form-control" name="body" rows="3"></textarea>
                                    <input type="hidden" name="product_id" class="form-control"
                                        value="{{ $product->id }}">
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Add Comment</button>
                                </div>
                            </form>

                            <hr>
                            <hr>
                            <a href="{{ route('products.index') }}" class="btn btn-primary">all products</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection